from enum import Enum

class AllureTags(str,Enum):
    AUTHORIZATION = "AUTHORIZATION"
    USER_MANAGEMENT = "USER_MANAGEMENT"
    VSPACE_MANAGEMENT = "VSAPCE_MANAGEMENT"
    DESKTOP_MANAGEMENT = "DESKTOP_MANAGEMENT"
    TEMPLATE_MANAGEMENT = "TEMPLATES_MANAGEMENT"
    ROLE_MODEL = "ROLE_MODEL"
    
